# Python Cheat Sheet

## Strings

In [21]:
s1 = "   This is a TEST"
s2 = "bag"
s3 = "This is a very long string that needs to be wrapped."

# Remove whitespace from start and end of string
stripped=s1.strip()
print(f"Stripped: '{stripped}'")

# Reverse upper/lower case 
swapcase = s1.swapcase()
print(f"Swapcase: {swapcase}")

# Convert to uppercase
upper = s1.upper()
print(f"Uppercase: {upper}")

# Split by delimiter
split = s1.split(" ")
print(f"Split: {split}")

# Convert string into list of its characters
character_list = list(s1)
print(f"Character list: {character_list}")

# Join multiple strings with a delimiter
join = " + ".join([s1, s2])
print(f"Join: {join}")

# Replace substring
replace = s1.replace("TEST","FROG")
print(f"Replace substring: {replace}")

# Change letter at specified position in string
l=list(s1)
l[10]="F"
new_string="".join(l)
print(f"Change character: {new_string}")

# String validation methods
is_alnum = s2.isalnum() # (a-z, A-Z and 0-9)
is_alpha = s2.isalpha() # (a-z, A-Z)
is_decimal = s2.isdecimal() # (0-9)
is_lower = s2.islower() # (a-z)
is_upper = s2.isupper() # (A-Z)
print(f"Is alphanumeric: {is_alnum}")
print(f"Is alphabetic: {is_alpha}")
print(f"Is decimal: {is_decimal}")
print(f"Is lowercase: {is_lower}")
print(f"Is uppercase: {is_upper}")

# Wrap text 
import textwrap
wrapped_text_string = textwrap.fill(s3,30)
wrapped_text_array = textwrap.wrap(s3,30)
print(f"\nWrapped text:\n{wrapped_text_string}\n")
print(f"Wrapped text as array:{wrapped_text_array}")

# Get character at position in alphabet
fifth_letter = chr(ord('a') + 4)
print(f"Fifth letter of alphabet: {fifth_letter}")

Stripped: 'This is a TEST'
Swapcase:    tHIS IS A test
Uppercase:    THIS IS A TEST
Split: ['', '', '', 'This', 'is', 'a', 'TEST']
Character list: [' ', ' ', ' ', 'T', 'h', 'i', 's', ' ', 'i', 's', ' ', 'a', ' ', 'T', 'E', 'S', 'T']
Join:    This is a TEST + bag
Replace substring:    This is a FROG
Change character:    This isFa TEST
Is alphanumeric: True
Is alphabetic: True
Is decimal: False
Is lowercase: True
Is uppercase: False

Wrapped text:
This is a very long string
that needs to be wrapped.

Wrapped text as array:['This is a very long string', 'that needs to be wrapped.']
Fifth letter of alphabet: e


## Regular Expressions (RegEx)

In [10]:
import re

# re.search(pattern, string) - search for pattern in string
# re.match(pattern, string) - match pattern at start of string

# re.split(pattern, string) - split string by pattern

m = re.search(r'\d+','1234abc')
print(f"End of match: {m.end()}")
print(f"Start of match: {m.start()}")
print(f"Matched string: {m.group()}")

End of match: 4
Start of match: 0
Matched string: 1234


## Lists

### Creating Lists

In [22]:
# Initialize empty list
list_empty = list()  # Initializing a list
print(f"Empty list: {list_empty}")

# Directly assigning values to a list
list_direct = [1, 2]
print(f"Directly assigned list: {list_direct}")

# Nested lists
students = [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41], ['Harsh', 39]]
print(f"Nested list: {students}")

Empty list: []
Directly assigned list: [1, 2]
Nested list: [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41], ['Harsh', 39]]


### Modifying Lists

In [23]:
arr = [1, 2, 3, 4, 5]

# Add single element to end of list
arr.append(9)   
print(f"After append: {arr}")

# Extend list by appending elements from iterable
arr.extend([10,11])
print(f"After extend: {arr}")

# Insert element at given position
arr.insert(3,7) # Insert 7 at index 3
print(f"After insert: {arr}")

# Remove first occurence of value
arr.remove(10) 
print(f"After remove: {arr}")

# Sort the list
arr.sort()
print(f"After sort: {arr}")

# Reverse the list
arr.reverse()
print(f"After reverse: {arr}")


After append: [1, 2, 3, 4, 5, 9]
After extend: [1, 2, 3, 4, 5, 9, 10, 11]
After insert: [1, 2, 3, 7, 4, 5, 9, 10, 11]
After remove: [1, 2, 3, 7, 4, 5, 9, 11]
After sort: [1, 2, 3, 4, 5, 7, 9, 11]
After reverse: [11, 9, 7, 5, 4, 3, 2, 1]


### List Operations

In [24]:
# Sum of list elements
total = sum(arr)
print(f"Sum of list: {total}")

# Length of list
length = len(arr)
print(f"Length of list: {length}")

# Get index of first occurence of value
index = arr.index(3)
print(f"Index of first occurrence of 3: {index}")

# Count occurences of value
count = arr.count(1)
print(f"Count of 1 in list: {count}")

# Remove and return item at given position (default last)
popped_value=arr.pop()
print(f"Popped value: {popped_value}, List after pop: {arr}")

# Get unique and sorted values from a list
arr = [3,1,4,2,3,4,1]
unique_sorted_list = sorted(set(arr))
print(f"Unique and sorted list: {unique_sorted_list}")

Sum of list: 42
Length of list: 8
Index of first occurrence of 3: 5
Count of 1 in list: 1
Popped value: 1, List after pop: [11, 9, 7, 5, 4, 3, 2]
Unique and sorted list: [1, 2, 3, 4]


### List Comprehensions

In [25]:
# List comprehension examples
l1 = [x for x in range(10) if x % 3 == 0] # Multiples of 3 below 10
print(f"Multiples of 3 below 10: {l1}")

l2 = [[i,j,k] for i in range(0,3) for j in range(0,2) for k in range(0,1) if i + j + k != 2] # All combinations of i,j,k where i+j+k != 2
print(f"All combinations of i,j,k where i+j+k != 2: {l2}")

Multiples of 3 below 10: [0, 3, 6, 9]
All combinations of i,j,k where i+j+k != 2: [[0, 0, 0], [0, 1, 0], [1, 0, 0], [2, 1, 0]]


## Sets

### Creating Sets

In [26]:
# Initialize empty set
set_empty = set()  # Initializing a set
print(f"Empty set: {set_empty}")

# Directly assigning values to a set
set_direct = {1, 2}
print(f"Directly assigned set: {set_direct}")

# String to set
set_string = set('HackerRank')
print(f"Set from string: {set_string}")

# List to set
set_list = set([1,2,1,2,3,4,5,6,0,9,12,22,3])
print(f"Set from list: {set_list}")

# Tuple to set
set_tuple = set((1,2,3,4,5,5))
print(f"Set from tuple: {set_tuple}")

# Set to set (removes duplicates)
set_set = set(set(['H','a','c','k','e','r','r','a','n','k']))
print(f"Set from dictionary: {set_set}")

# Dictionary to set (gets keys only)
set_dict = set({'Hacker' : 'DOSHI', 'Rank' : 616 })
print(f"Set from dictionary: {set_dict}")

# Enumerate to set (creates tuples of index, value)
set_enumerate = set(enumerate(['H','a','c','k','e','r','r','a','n','k']))
print(f"Set from enumerate: {set_enumerate}")


Empty set: set()
Directly assigned set: {1, 2}
Set from string: {'H', 'R', 'e', 'c', 'n', 'r', 'a', 'k'}
Set from list: {0, 1, 2, 3, 4, 5, 6, 9, 12, 22}
Set from tuple: {1, 2, 3, 4, 5}
Set from dictionary: {'n', 'H', 'r', 'a', 'e', 'c', 'k'}
Set from dictionary: {'Rank', 'Hacker'}
Set from enumerate: {(5, 'r'), (6, 'r'), (0, 'H'), (1, 'a'), (4, 'e'), (2, 'c'), (9, 'k'), (8, 'n'), (7, 'a'), (3, 'k')}


### Modifying Sets

In [27]:
set1 = set([1,2,3])

# Add element to set
set1.add('H')
print(f"Set after character addition: {set1}")

set1.add((4, 'a'))
print(f"Set after tuple addition: {set1}")

# Add multiple elements to set
# update() only works for iterable objects
set1.update([5, 'b'])
print(f"Set after update: {set1}")

# Remove specified element from set
set1.remove(2)  # Raises KeyError if element not found
print(f"Set after remove: {set1}")

set1.discard('b')  # Does not raise error if element not found
print(f"Set after discard: {set1}")

# Remove and return an arbitrary element from the set
arbitrary_element = set1.pop()
print(f"Popped element: {arbitrary_element}, Set after pop: {set1}")

Set after character addition: {1, 2, 3, 'H'}
Set after tuple addition: {1, 2, 3, 'H', (4, 'a')}
Set after update: {1, 2, 3, 'H', 5, 'b', (4, 'a')}
Set after remove: {1, 3, 'H', 5, 'b', (4, 'a')}
Set after discard: {1, 3, 'H', 5, (4, 'a')}
Popped element: 1, Set after pop: {3, 'H', 5, (4, 'a')}


### Set Operations

In [28]:
set1 = set([1,2,3])
set2 = set([3,4,5])

# Sum of set elements
total = sum(set1)
print(f"Sum of set 1: {total}")

# Length of set
length = len(set1)
print(f"Length of set1: {length}")

# Union
union = set1.union(set2) # Values which exist in set1 OR set2, output is a new set
set1.update(set2) # Updates set1 with elements from set2
print(f"Union of set1 and set2: {union}")

# Intersection
intersection = set1.intersection(set2) # Values which exist in set1 AND set2, output is a new set
set1.intersection_update(set2) # Updates set1 with elements from the intersection
print(f"Intersection of set1 and set2: {intersection}")

# Difference
difference = set1.difference(set2) # Values which exist in a but NOT in b, output is a new set
set1.difference_update(set2) # Updates set1 with elements from the difference
print(f"Difference of set1 and set2: {difference}")  

# Symmetric Difference
symm_difference = set1.symmetric_difference(set2) # Values which exist in a but NOT in b, output is a new set
set1.symmetric_difference_update(set2) # Updates set1 with elements from the symmetric difference
print(f"Symmetric difference of set1 and set2: {symm_difference}") # Values which exist in a OR B but not both


Sum of set 1: 6
Length of set1: 3
Union of set1 and set2: {1, 2, 3, 4, 5}
Intersection of set1 and set2: {3, 4, 5}
Difference of set1 and set2: set()
Symmetric difference of set1 and set2: {3, 4, 5}


## Tuples

Tuples are data structures that look a lot like lists. Unlike lists, tuples are immutable (meaning that they cannot be modified once created). This restricts their use because we cannot add, remove, or assign values. 

However, they are useful for unchanging data to ensure that they are not changed accidentally. Additionally, unlike lists, tuples can be used as keys in a dictionary, e.g.:

```python

location_data = {
    (51.5072, 0.1276): "London",
    (40.7128, -74.0060): "New York"
}

```

## Creating Tuples

In [29]:
# List to tuple
t = tuple([5, 8, 7, 9])
print(f"Tuple from list: {t}")

a=5
b=10

# A common tuple use is the swapping of  numbers:
a, b = b, a
print(f"After swapping: a={a}, b={b}")

Tuple from list: (5, 8, 7, 9)
After swapping: a=10, b=5


## Numpy

In [35]:
import numpy as np

# --- Numpy Arrays ---

# Initialize numpy arrays with different data types
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"Array with default dtype (int): {arr}")
arr_float = np.array([1, 2, 3], float)
print(f"Array with float dtype: {arr_float}")

# Get shape of array
print(f"Shape of array: {arr.shape}")

# Reshape array
arr = arr.reshape((3,2))
arr.shape = (3,2)  # Alternative way to reshape
print(f"Reshaped array (3,2):\n{arr}")

# Transpose array
arr = arr.transpose()
print(f"Transposed array:\n{arr}")

# Flatten array
arr = arr.flatten()
print(f"Flattened array: {arr}")

# Concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_concat = np.concatenate((arr1, arr2))
print(f"Array 1: {arr1}, Array 2: {arr2}, Concatenated array: {arr_concat}")

# Zeros and Ones
zeros_array = np.zeros((2,3))
print(f"Array of zeros (2,3):\n{zeros_array}")
ones_array = np.ones((3,2))
print(f"Array of ones (3,2):\n{ones_array}")

# Identity matrix
identity_matrix = np.eye(3)
print(f"Identity matrix (3x3):\n{identity_matrix}")

# Eye matrix
eye_matrix = np.eye(3, 4, k=1)  # 3 rows, 4 columns, diagonal offset by 1
print(f"Eye matrix (3x4) with k=1:\n{eye_matrix}")

# Floor, ceil, round, rint
arr = np.array([1.2, 2.5, 3.7])
print(f"Original array: {arr}")
print(f"Floor: {np.floor(arr)}")
print(f"Ceil: {np.ceil(arr)}")
print(f"Round: {np.round(arr)}") # Round to nearest integer
print(f"Rint: {np.rint(arr)}") # Round to nearest integer, but returns float

# min, max, sum, prod, mean, std, var
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array:\n{arr}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Sum: {np.sum(arr)}")
print(f"Product: {np.prod(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Standard Deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")


Array with default dtype (int): [1 2 3 4 5 6]
Array with float dtype: [1. 2. 3.]
Shape of array: (6,)
Reshaped array (3,2):
[[1 2]
 [3 4]
 [5 6]]
Transposed array:
[[1 3 5]
 [2 4 6]]
Flattened array: [1 3 5 2 4 6]
Array 1: [1 2 3], Array 2: [4 5 6], Concatenated array: [1 2 3 4 5 6]
Array of zeros (2,3):
[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones (3,2):
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eye matrix (3x4) with k=1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Original array: [1.2 2.5 3.7]
Floor: [1. 2. 3.]
Ceil: [2. 3. 4.]
Round: [1. 2. 4.]
Rint: [1. 2. 4.]
Array:
[[1 2 3]
 [4 5 6]]
Min: 1
Max: 6
Sum: 21
Product: 720
Mean: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665


## Print

In [30]:
x = 2.1894023
s = "test"

# Print text with variable substitution
print(f"Value of x to 2 decimal places is {x:.2f} and string is {s}.")

# Text alignment
width = 20
print(s.center(width, "*"))
print(s.ljust(width, "*"))
print(s.rjust(width, "*"))

Value of x to 2 decimal places is 2.19 and string is test.
********test********
test****************
****************test


## Itertools

In [31]:
import itertools

# Cartesian product
cartesian_product = list(itertools.product([1,2,3],repeat = 2))
print(f"Cartesian product with repeat=2: {cartesian_product}")
cartesian_product = list(itertools.product([1,2,3],[3,4]))
print(f"Cartesian product of [1,2,3] and [3,4]: {cartesian_product}")
A = [[1,2,3],[3,4,5]]
cartesian_productlist = list(itertools.product(*A))
print(f"Cartesian product of lists in A ({A}): {cartesian_productlist}")

# Permutations
permutations = list(itertools.permutations([1,2,3],2))
print(f"\nPermutations of [1,2,3] with length 2: {permutations}")
permutations = list(itertools.permutations([1,2,3]))
print(f"Permutations of [1,2,3] with length 3: {permutations}")
permutations = list(itertools.permutations('abc',2))
print(f"Permutations of string 'abc' with length 2: {permutations}")

# Combinations
combinations = list(itertools.combinations([1,2,3],2))
print(f"\nCombinations of [1,2,3] with length 2: {combinations}")
combinations = list(itertools.combinations([1,2,3],3))
print(f"Combinations of [1,2,3] with length 3: {combinations}")
combinations = list(itertools.combinations('abc',2))
print(f"Combinations of string 'abc' with length 2: {combinations}")

# Combinations with replacement
combinations_with_replacement = list(itertools.combinations_with_replacement([1,2,3],2))
print(f"\nCombinations with replacement of [1,2,3] with length 2: {combinations_with_replacement}")
combinations_with_replacement = list(itertools.combinations_with_replacement([1,2,3],3))
print(f"Combinations with replacement of [1,2,3] with length 3: {combinations_with_replacement}")
combinations_with_replacement = list(itertools.combinations_with_replacement('abc',2))
print(f"Combinations with replacement of string 'abc' with length 2: {combinations_with_replacement}")

# Groupby
groupby = {k: list(v) for k, v in itertools.groupby('aaabbbccdaa')}
print(f"\nGroupby of 'aaabbbccdaa': {groupby}")




Cartesian product with repeat=2: [(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
Cartesian product of [1,2,3] and [3,4]: [(1, 3), (1, 4), (2, 3), (2, 4), (3, 3), (3, 4)]
Cartesian product of lists in A ([[1, 2, 3], [3, 4, 5]]): [(1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5)]

Permutations of [1,2,3] with length 2: [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]
Permutations of [1,2,3] with length 3: [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
Permutations of string 'abc' with length 2: [('a', 'b'), ('a', 'c'), ('b', 'a'), ('b', 'c'), ('c', 'a'), ('c', 'b')]

Combinations of [1,2,3] with length 2: [(1, 2), (1, 3), (2, 3)]
Combinations of [1,2,3] with length 3: [(1, 2, 3)]
Combinations of string 'abc' with length 2: [('a', 'b'), ('a', 'c'), ('b', 'c')]

Combinations with replacement of [1,2,3] with length 2: [(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]
Combinations with replacement of [1,2,3] with length 3: [(1

## Collections

In [32]:
# Collections
from collections import Counter, defaultdict, namedtuple, OrderedDict, deque

# Counter - counts the occurences of elements in an iterable
count = Counter(['a','b','c','a','b','b','d','a'])
keys = count.keys()
values = count.values()
items = count.items()
elements = count.elements()
most_common = count.most_common(2)
print(f"Element counts: {count}")
print(f"Keys: {list(keys)}")
print(f"Values: {list(values)}")
print(f"Items: {items}")
print(f"Elements: {list(elements)}")
print(f"Most common 2 elements: {most_common}")

# DefaultDict - dictionary with default value for nonexistent keys (normal dict does not allow this)
dd = defaultdict(list) # Default value is an empty list
dd['a'].append(1)
dd['b'].append(2)
print(f"\nDefaultDict: {[item for item in dd.items()]}")
print(f"Accessing existing key 'a': {dd['a']}")
print(f"Accessing non-existing key 'c': {dd['c']}")

# NamedTuple - lightweight object type similar to a struct with named fields
Point = namedtuple('Point', ['x', 'y'])
p1 = Point(2,3)
p2 = Point(x=5, y=7)
dot_product = p1.x * p2.y + p1.y * p2.x
print(f"Dot product of p1 and p2: {dot_product}")
Car = namedtuple('Car', ['make', 'model', 'year'])
car1 = Car('Toyota', 'Camry', 2020)
print(f"Car make: {car1.make}, model: {car1.model}, year: {car1.year}")

# OrderedDict - dictionary that maintains insertion order (normal dict maintains insertion order as of Python 3.7+)
od = OrderedDict()
od['a'] = 1
od['b'] = 2
od['c'] = 3
print(f"\nOrderedDict: {od}")

# deque - double-ended queue for efficient appends and pops from both ends
dq = deque()
dq.append(1) # Append right 
dq.append([2,3,4]) # Append right as single element (a list)
dq.appendleft(0) # Append left
print(f"\nDeque after appends: {dq}")
dq.extend([5,6,7]) # Extend right (from iterable)
dq.extendleft([-2,-1]) # Extend left (note: order is reversed)
print(f"Deque after extends: {dq}")
pop=dq.pop() # Pop right
print(f"Popped value from right: {pop}")
pop_left=dq.popleft() # Pop left
print(f"Popped value from left: {pop_left}")
print(f"Deque after pops: {dq}")
dq.remove(5) # Remove first occurrence of value
print(f"Deque after removing 5: {dq}")
dq.reverse() # Reverse the deque
print(f"Deque after reverse: {dq}")
dq.rotate(2) # Rotate right by 2
print(f"Deque after rotating right by 2: {dq}")
dq.rotate(-3) # Rotate left by 3
print(f"Deque after rotating left by 3: {dq}")
count = dq.count(2) # Count occurrences of value
print(f"Count of 2 in deque: {count}")
dq.clear() # Clear the deque
print(f"Deque after clear: {dq}")

Element counts: Counter({'a': 3, 'b': 3, 'c': 1, 'd': 1})
Keys: ['a', 'b', 'c', 'd']
Values: [3, 3, 1, 1]
Items: dict_items([('a', 3), ('b', 3), ('c', 1), ('d', 1)])
Elements: ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'd']
Most common 2 elements: [('a', 3), ('b', 3)]

DefaultDict: [('a', [1]), ('b', [2])]
Accessing existing key 'a': [1]
Accessing non-existing key 'c': []
Dot product of p1 and p2: 29
Car make: Toyota, model: Camry, year: 2020

OrderedDict: OrderedDict({'a': 1, 'b': 2, 'c': 3})

Deque after appends: deque([0, 1, [2, 3, 4]])
Deque after extends: deque([-1, -2, 0, 1, [2, 3, 4], 5, 6, 7])
Popped value from right: 7
Popped value from left: -1
Deque after pops: deque([-2, 0, 1, [2, 3, 4], 5, 6])
Deque after removing 5: deque([-2, 0, 1, [2, 3, 4], 6])
Deque after reverse: deque([6, [2, 3, 4], 1, 0, -2])
Deque after rotating right by 2: deque([0, -2, 6, [2, 3, 4], 1])
Deque after rotating left by 3: deque([[2, 3, 4], 1, 0, -2, 6])
Count of 2 in deque: 0
Deque after clear: deque([])


## Date and Time

In [33]:
import calendar
from datetime import datetime

# Get weekday of a specific date
weekday = calendar.weekday(2024, 6, 15)  # Year, Month, Day
day_names = list(calendar.day_name)
print(f"Weekday of 15th June 2024: {day_names[weekday]}")

# Date and Time

# Absolute difference between two dates in seconds
date1 = "Sun 10 May 2015 13:54:36 -0700"
date2 = "Mon 11 May 2015 14:54:36 -0700"
fmt = "%a %d %b %Y %H:%M:%S %z"
d1 = datetime.strptime(date1, fmt)
d2 = datetime.strptime(date2, fmt)
delta = d2 - d1
print(f"Absolute difference between dates in seconds: {abs(int(delta.total_seconds()))}")

Weekday of 15th June 2024: Saturday
Absolute difference between dates in seconds: 90000


## Inbuilt math

In [34]:
# Inbuilt math

# divmod
print(f"divmod(7,3): {divmod(7,3)}")  # Outputs (2,1)

# power
print(f"2**3: {2**3}") # 2 to the power of 3
print(f"pow(2,3): {pow(2,3)}")  # 2 to the power of 3
print(f"pow(2,3,3): {pow(2,3,3)}")  # 2 to the power of 3 mod 3

divmod(7,3): (2, 1)
2**3: 8
pow(2,3): 8
pow(2,3,3): 2


## math and cmath

In [35]:
import math, cmath

# Polar coordinates
z = 1 + 2j
r, theta = cmath.polar(z)
r = abs(z)
theta = cmath.phase(z)
print(f"Polar coordinates of {z}: r={r}, theta={theta}")

# Angles
tan = math.tan(math.radians(45))
print(f"Tangent of 45 degrees: {tan}")

Polar coordinates of (1+2j): r=2.23606797749979, theta=1.1071487177940904
Tangent of 45 degrees: 0.9999999999999999


## Exceptions

In [36]:
# Zero division handling
try:
    result = 5 / 0
except ZeroDivisionError as e:
    print(f"Error: {e}")

# Value error handling
try:
    num = int("abc")
except ValueError as e:
    print(f"Error: {e}")

# Regex error handling
import re
try:
    pattern = re.compile("[A-")
except re.error as e:
    print(f"Error: {e}")

Error: division by zero
Error: invalid literal for int() with base 10: 'abc'
Error: unterminated character set at position 0


## Built-Ins

In [37]:
# zip([iterable1], [iterable2], ... )
# Combines multiple iterables into tuples, if the iterables are of unequal length, it stops at the shortest one
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c', 'd']
zipped = list(zip(list1, list2))
print(f"Zipped list: {zipped}")

# eval
x = 10
expression = "x * 2 + 5"
result = eval(expression)
print(f"Result of eval('{expression}'): {result}")

# input
user_input = input("Enter something: ")
print(f"You entered: {user_input}")

# any() and all()
bool_list = [True, True, False]
any_result = any(bool_list)  # True if any element is True
all_result = all(bool_list)  # True if all elements are True
print(f"Any True in list: {any_result}")
print(f"All True in list: {all_result}")

# sorted()
all_items = [('apple', 2), ('banana', 3), ('cherry', 1), ('date', 3)]
sorted_items = sorted(all_items, key=lambda x: (-x[1], x[0]))  # Sort by second item descending, then first item ascending
print(f"Sorted items: {sorted_items}")

Zipped list: [(1, 'a'), (2, 'b'), (3, 'c')]
Result of eval('x * 2 + 5'): 25
You entered: 
Any True in list: True
All True in list: False
Sorted items: [('banana', 3), ('date', 3), ('apple', 2), ('cherry', 1)]


## Functionals

In [38]:
# Functionals

#lambda function - single line anonymous function
double = lambda x: x * 2
print(f"Double of 5 using lambda: {double(5)}")

# map(function, iterable)
numbers = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, numbers))
print(f"Squared numbers using map: {squared}")

# reduce(function, iterable)
from functools import reduce
product = reduce(lambda x, y: x * y, numbers)
print(f"Product of numbers using reduce: {product}")    

Double of 5 using lambda: 10
Squared numbers using map: [1, 4, 9, 16, 25]
Product of numbers using reduce: 120


## Classes

In [39]:
# Classes
# built-in methods
class Sample:
    def __init__(self, value):
        self.value = value

    def __add__(self, other): # Overloading the + operator
        return Sample(self.value + other.value)
    def __sub__(self, other): # Overloading the - operator
        return Sample(self.value - other.value)
    def __mul__(self, other): # Overloading the * operator
        return Sample(self.value * other.value)
    def __truediv__(self, other): # Overloading the / operator
        return Sample(self.value / other.value)
    def __str__(self): # String representation, overloading str()
        return f"Sample({self.value})"


## Other

In [40]:
#mapping
# n, m = map(int,input().split())
# array = list(map(int, input().split()))
# A = set(map(int, input().split()))
# B = set(map(int, input().split()))

#modulo operator
#gives you the remainder left over after a division
print(7 % 3)  # Outputs 1
print(3 % 7)  # Outputs 3

# floor division - rounds down to the nearest whole number
print(7//4) # Outputs 1

# exponentiation
print(5**2) # Outputs 25

# getattr() function
getattr(A, command[0])(B)

1
3
1
25


NameError: name 'command' is not defined